### PR TITLE
Fixed Legal Issue :D

### PR DESCRIPTION
**Pull request by RandomGamingDev**
Replaced your GPL-3.0 license with AGPL-3.0 license due to usage and modification of [exclude.confg](https://github.com/robertdavidgraham/masscan/blob/master/data/exclude.conf) from the AGPL-3.0 [masscan](https://github.com/robertdavidgraham/masscan/) repository.

### CODE REVIEW

**Comment by RandomGamingDev** [comment]
More info available here: https://github.com/RandomGamingDev/EzCopenheimer/issues/5#issuecomment-2128287452

**Comment by JacobDevWasTaken** [comment]
Thanks, do i also need to change the tcp server code to allow a user to see the source? In that case, is simply linking this repo enough?

**Comment by RandomGamingDev** [comment]
> Thanks, do i also need to change the tcp server code to allow a user to see the source? In that case, is simply linking this repo enough?

Yes, your code should be changed to "if the program is expressly designed to accept user requests and send responses over a network, the user is entitled to receive the source code of the version being used" (FSF, [The fundamentals of the AGPLv3](https://www.fsf.org/bulletin/2021/fall/the-fundamentals-of-the-agplv3)) and linking it should be more than enough.

**Comment by JacobDevWasTaken** [comment]
> > Thanks, do i also need to change the tcp server code to allow a user to see the source? In that case, is simply linking this repo enough?
> 
> Yes, your code should be changed to "if the program is expressly designed to accept user requests and send responses over a network, the user is entitled to receive the source code of the version being used" (FSF, [The fundamentals of the AGPLv3](https://www.fsf.org/bulletin/2021/fall/the-fundamentals-of-the-agplv3)) and linking it should be more than enough.

thanks

**Pull request merged**
